# Generated by Django 2.2.4 on 2019-08-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='name',
            new_name='first',
        ),
    ]
